#!/usr/bin/env python3
"""PreToolUse advisory: run the project's formatters over staged files.

Fires on `git commit`, checks the staged files for each enabled language, and
reports what to run. It never blocks: a formatting nit is trivially fixable, and
a blocked commit costs more than the nit.

Silent in two cases that matter. A repository with no recognised language gets
nothing, and a repository where the pre-commit framework already owns commit-time
checks gets nothing either, because re-running the same formatters here would be
duplicate work and a duplicate nag.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from quality_common import (  # noqa: E402
    emit_advisory,
    find_repo_root,
    language_enabled,
    payload_command,
    payload_cwd,
    read_payload,
    selected_languages,
)

# `git commit` where commit is the subcommand, so `git -C path commit` fires while
# `git log --grep commit` does not.
GIT_COMMIT = re.compile(
    r"(?:^|[\s/])git(?:\s+-[^\s]+(?:\s+[^-][^\s;&|]*)?)*\s+commit(?:$|\s)"
)
SKIP_MARKER = re.compile(r"\[skip[ -]lint\]", re.IGNORECASE)


def run(args: list[str], cwd: Path, timeout: int = 60) -> tuple[int, str]:
    import subprocess

    try:
        result = subprocess.run(
            args, cwd=cwd, capture_output=True, text=True, timeout=timeout
        )
    except (OSError, subprocess.SubprocessError):
        return 0, ""  # a missing or failed tool is a tooling gap, not a finding
    return result.returncode, result.stdout + result.stderr


def have(tool: str) -> bool:
    import shutil

    return shutil.which(tool) is not None


def staged_files(root: Path) -> list[str]:
    code, output = run(["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"], root)
    if code != 0:
        return []
    return [line for line in output.splitlines() if line.strip()]


def precommit_owns_checks(root: Path) -> bool:
    """True when the pre-commit framework already runs these checks on commit.

    Requires a config AND an installed framework hook: a config alone proves
    nothing, since nobody may have run the install. A hooks path outside the
    repository belongs to some other manager, which this cannot reason about, so
    it does not count as the framework.
    """
    if not any((root / name).is_file() for name in (".pre-commit-config.yaml", ".pre-commit-config.yml")):
        return False

    code, output = run(["git", "rev-parse", "--git-path", "hooks"], root, timeout=10)
    if code != 0:
        return False
    hooks = Path(output.strip())
    if not hooks.is_absolute():
        hooks = root / hooks
    try:
        if not hooks.resolve().is_relative_to(root.resolve()):
            return False
    except (OSError, ValueError):
        return False

    hook = hooks / "pre-commit"
    try:
        return "generated by pre-commit" in hook.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def check_go(files: list[str], root: Path) -> list[str]:
    targets = [f for f in files if f.endswith(".go")]
    if not targets or not have("gofmt"):
        return []
    code, output = run(["gofmt", "-l", *targets], root)
    unformatted = [line for line in output.splitlines() if line.strip()]
    if unformatted:
        return [f"Go formatting is required before commit. Run: gofmt -w {' '.join(unformatted)}"]
    return []


def check_python(files: list[str], root: Path) -> list[str]:
    targets = [f for f in files if f.endswith((".py", ".pyi"))]
    if not targets:
        return []
    if have("uv") and (root / "pyproject.toml").is_file():
        prefix = ["uv", "run", "ruff"]
        label = "uv run ruff"
    elif have("ruff"):
        prefix = ["ruff"]
        label = "ruff"
    else:
        return []
    findings = []
    if run([*prefix, "check", *targets], root)[0] != 0:
        findings.append(f"Python lint failed before commit. Run: {label} check --fix")
    if run([*prefix, "format", "--check", *targets], root)[0] != 0:
        findings.append(f"Python formatting failed before commit. Run: {label} format")
    return findings


def check_rust(files: list[str], root: Path) -> list[str]:
    if not any(f.endswith(".rs") for f in files):
        return []
    if not have("cargo") or not (root / "Cargo.toml").is_file():
        return []
    if run(["cargo", "fmt", "--all", "--", "--check"], root, timeout=120)[0] != 0:
        return ["Rust formatting is required before commit. Run: cargo fmt --all"]
    return []


def check_ts(files: list[str], root: Path) -> list[str]:
    targets = [f for f in files if f.endswith((".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"))]
    if not targets:
        return []
    for runner, label in (
        (["bunx", "--bun", "biome"], "bunx --bun biome"),
        (["pnpm", "exec", "biome"], "pnpm exec biome"),
        (["npx", "biome"], "npx biome"),
    ):
        if have(runner[0]):
            if run([*runner, "check", *targets], root, timeout=120)[0] != 0:
                return [f"Biome check failed before commit. Run: {label} check --write"]
            return []
    return []


CHECKERS = {"go": check_go, "python": check_python, "rust": check_rust, "ts": check_ts}


def main() -> int:
    payload = read_payload()
    if not payload:
        return 0

    command = payload_command(payload)
    if not command or not GIT_COMMIT.search(command):
        return 0
    if SKIP_MARKER.search(command):
        return 0

    root = find_repo_root(payload_cwd(payload))
    if root is None:
        return 0

    selected = selected_languages(root)
    if not selected:
        return 0
    if precommit_owns_checks(root):
        return 0

    files = staged_files(root)
    if not files:
        return 0

    findings: list[str] = []
    for language, checker in CHECKERS.items():
        if language_enabled(language, selected):
            findings.extend(checker(files, root))

    if findings:
        emit_advisory(
            "Quality advisory before commit (non-blocking):\n"
            + "\n".join(f"- {finding}" for finding in findings)
            + "\nAdd [skip lint] to the commit message to suppress."
        )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except BaseException:
        # Fail open: a formatting nudge must never wedge a commit.
        raise SystemExit(0)
