#!/usr/bin/env bash
set -euo pipefail

payload="$(cat 2>/dev/null || true)"
command -v jq >/dev/null 2>&1 || exit 0

# Cheap pre-jq bail: this guard acts ONLY on `git commit` commands, so if the raw
# payload contains no `commit` token there is nothing to inspect. Skips the jq
# spawn (the dominant per-call cost) for the common case on the hot path. Pure
# SUPERSET filter on literal bytes — the command still has to survive the
# structured checks below — so it can never mask a command jq would have flagged.
case "$payload" in
  *commit*) ;;
  *) exit 0 ;;
esac

command="$(printf '%s' "$payload" | jq -r 'if (.tool_input|type)=="string" then .tool_input else (.tool_input.command // empty) end' 2>/dev/null || true)"
if ! printf '%s' "$command" | grep -Eq '(^|[[:space:]])git([[:space:]][^;&|]*)?[[:space:]]+commit($|[[:space:]])'; then
  exit 0
fi

# Bypass: honor an explicit [skip lint] marker in the commit command/message.
if printf '%s' "$command" | grep -Eiq '\[skip[ -]lint\]'; then
  exit 0
fi

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
[[ -n "$repo_root" ]] || exit 0
cd "$repo_root"

# Defer to the pre-commit framework when it OWNS this repo's commit-time quality.
# If a .pre-commit-config.yaml exists AND the framework's git hook is installed,
# pre-commit already runs the same formatters/linters (ruff, biome, gofumpt,
# rustfmt, ...) on commit — re-running them here in --check mode is duplicate
# work and a duplicate nag. This hook then serves only as the FALLBACK for repos
# that have not adopted pre-commit. Resolve the hooks dir honoring a custom
# core.hooksPath; an external (corporate) hooksPath is not pre-commit, so we do
# NOT defer in that case (the fallback advisory still adds value).
if [[ -f .pre-commit-config.yaml || -f .pre-commit-config.yml ]]; then
  pc_hooks_dir="$(git config --get core.hooksPath 2>/dev/null || true)"
  if [[ -n "$pc_hooks_dir" ]]; then
    case "$pc_hooks_dir" in /*) : ;; *) pc_hooks_dir="$repo_root/$pc_hooks_dir" ;; esac
  else
    pc_git_dir="$(git rev-parse --git-common-dir 2>/dev/null || git rev-parse --git-dir 2>/dev/null || true)"
    case "$pc_git_dir" in /*) : ;; *) pc_git_dir="$repo_root/$pc_git_dir" ;; esac
    pc_hooks_dir="$pc_git_dir/hooks"
  fi
  # Only defer when the installed hook is the pre-commit framework's (marker),
  # and it lives inside this repo (an external manager is not pre-commit).
  case "$pc_hooks_dir/" in
    "$repo_root"/*)
      if [[ -f "$pc_hooks_dir/pre-commit" ]] \
        && grep -q 'generated by pre-commit' "$pc_hooks_dir/pre-commit" 2>/dev/null; then
        exit 0
      fi
      ;;
  esac
fi

# Advisory (non-blocking) lint gate. Findings are accumulated and surfaced as
# additionalContext so the commit is never hard-blocked; the agent can act on
# the advice or proceed. Add [skip lint] to the commit message to suppress.
advisories=""
advise() {
  local reason="$1"
  if [[ -n "$advisories" ]]; then
    advisories="$advisories"$'\n'"- $reason"
  else
    advisories="- $reason"
  fi
}

selected_file=".agents/hooks/quality-languages"
selected=""
if [[ -f "$selected_file" ]]; then
  selected="$(tr '\n' ' ' < "$selected_file" | tr ',' ' ')"
elif [[ -n "${AGENTIC_QUALITY_LANGS:-}" ]]; then
  selected="${AGENTIC_QUALITY_LANGS//,/ }"
else
  # Conservative fallback for older projects. Only enable when clear project
  # markers exist; unknown projects should not be blocked by this hook.
  [[ -f go.mod ]] && selected="$selected go"
  [[ -f pyproject.toml ]] && selected="$selected python"
  [[ -f Cargo.toml ]] && selected="$selected rust"
  [[ -f package.json ]] && selected="$selected ts"
fi

has_lang() {
  local wanted="$1"
  printf ' %s ' "$selected" | grep -Eq " (all|$wanted) "
}

# Compute once: every language block reuses this, instead of re-running
# git diff per block (the hook fires on every commit attempt).
all_changed="$(
  git diff --cached --name-only --diff-filter=ACMR
  git diff --name-only --diff-filter=ACMR
)"

changed_files() {
  printf '%s\n' "$all_changed"
}

if has_lang go; then
  if command -v gofmt >/dev/null 2>&1; then
    go_files=()
    while IFS= read -r l; do
      [[ -n "$l" ]] && go_files+=("$l")
    done < <(changed_files | grep -E '\.go$' | sort -u)
    if [[ "${#go_files[@]}" -gt 0 ]]; then
      bad="$(gofmt -l "${go_files[@]}" 2>/dev/null || true)"
      [[ -z "$bad" ]] || advise "Go formatting is required before commit. Run: gofmt -w ${bad//$'\n'/ }"
    fi
  fi
fi

if has_lang python; then
  py_files=()
  while IFS= read -r l; do
    [[ -n "$l" ]] && py_files+=("$l")
  done < <(changed_files | grep -E '\.pyi?$' | sort -u)
  if [[ "${#py_files[@]}" -gt 0 ]]; then
    if command -v uv >/dev/null 2>&1 && [[ -f pyproject.toml ]]; then
      uv run ruff check "${py_files[@]}" >/tmp/agentic-ruff-check.log 2>&1 || advise "Python Ruff check failed before commit. Run: uv run ruff check --fix"
      uv run ruff format --check "${py_files[@]}" >/tmp/agentic-ruff-format.log 2>&1 || advise "Python Ruff format failed before commit. Run: uv run ruff format"
    elif command -v ruff >/dev/null 2>&1; then
      ruff check "${py_files[@]}" >/tmp/agentic-ruff-check.log 2>&1 || advise "Python Ruff check failed before commit. Run: ruff check --fix"
      ruff format --check "${py_files[@]}" >/tmp/agentic-ruff-format.log 2>&1 || advise "Python Ruff format failed before commit. Run: ruff format"
    fi
  fi
fi

if has_lang rust; then
  if command -v cargo >/dev/null 2>&1 && [[ -f Cargo.toml ]]; then
    if changed_files | grep -qE '\.rs$|Cargo\.toml$'; then
      cargo fmt --all -- --check >/tmp/agentic-cargo-fmt.log 2>&1 || advise "Rust formatting is required before commit. Run: cargo fmt --all"
    fi
  fi
fi

if has_lang ts || has_lang javascript || has_lang typescript; then
  js_files=()
  while IFS= read -r l; do
    [[ -n "$l" ]] && js_files+=("$l")
  done < <(changed_files | grep -E '\.(ts|tsx|js|jsx|mjs|cjs|vue|svelte)$' | sort -u)
  if [[ "${#js_files[@]}" -gt 0 ]]; then
    if [[ -f biome.json || -f biome.jsonc ]] || grep -q '"@biomejs/biome"\|"biome"' package.json 2>/dev/null; then
      if command -v bunx >/dev/null 2>&1; then
        bunx --bun biome check "${js_files[@]}" >/tmp/agentic-biome.log 2>&1 || advise "Biome check failed before commit. Run: bunx --bun biome check --write"
      elif command -v pnpm >/dev/null 2>&1; then
        pnpm exec biome check "${js_files[@]}" >/tmp/agentic-biome.log 2>&1 || advise "Biome check failed before commit. Run: pnpm exec biome check --write"
      elif command -v npx >/dev/null 2>&1; then
        npx biome check "${js_files[@]}" >/tmp/agentic-biome.log 2>&1 || advise "Biome check failed before commit. Run: npx biome check --write"
      fi
    fi
  fi
fi

# Non-blocking: surface accumulated findings as advisory context. The commit
# proceeds regardless (locked policy: lint gate is advisory, not a hard deny).
if [[ -n "$advisories" ]]; then
  ctx="QUALITY ADVISORY: lint/format issues detected before commit (non-blocking). Consider fixing, or add [skip lint] to the commit message to silence:"$'\n'"$advisories"
  jq -cn --arg ctx "$ctx" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "allow",
      permissionDecisionReason: $ctx,
      additionalContext: $ctx
    }
  }'
fi

exit 0
