#!/usr/bin/env python3
"""Compile APM global instructions into Claude and Codex root context files."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from pathlib import Path

import yaml


MARKER = "<!-- Generated by APM CLI from .apm/ primitives -->"
LINK_RE = re.compile(r"(\[[^\]]+\]\()([^)]+)(\))")


class CompileError(ValueError):
    pass


def instruction_files(module_root: Path) -> list[Path]:
    # .apm-resolution-staging holds leaked rollback copies of the same packages
    # (apm_cli/install/resolution_staging.py); walking them triples every pointer.
    return sorted(
        path
        for path in module_root.glob("**/.apm/instructions/*.md")
        if ".apm-resolution-staging" not in path.parts
    )


def instruction_body(path: Path) -> str | None:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return text.strip()
    try:
        _, frontmatter, body = text.split("---\n", 2)
    except ValueError as exc:
        raise CompileError(f"malformed frontmatter: {path}") from exc
    metadata = yaml.safe_load(frontmatter) or {}
    if metadata.get("applyTo") or metadata.get("apply_to"):
        return None
    return body.strip()


def rewrite_links(body: str, source: Path, destination: Path) -> str:
    def replace(match: re.Match[str]) -> str:
        target = match.group(2).strip()
        if target.startswith(("#", "/", "http://", "https://", "mailto:")):
            return match.group(0)
        path_text, separator, fragment = target.partition("#")
        resolved = (source.parent / path_text).resolve()
        if not resolved.exists():
            raise CompileError(f"broken instruction link in {source}: {target}")
        relative = os.path.relpath(resolved, destination.parent)
        rewritten = relative + (separator + fragment if separator else "")
        return f"{match.group(1)}{rewritten}{match.group(3)}"

    return LINK_RE.sub(replace, body)


def expected_content(module_root: Path, destination: Path) -> str:
    sections: list[str] = []
    for path in instruction_files(module_root):
        body = instruction_body(path)
        if body:
            sections.append(rewrite_links(body, path, destination))
    if not sections:
        raise CompileError(f"no global instructions found below {module_root}")
    payload = "\n\n".join(sections).strip() + "\n"
    build_id = hashlib.sha256(payload.encode("utf-8")).hexdigest()[:12]
    return f"{MARKER}\n<!-- Build ID: {build_id} -->\n\n{payload}"


def sync_file(module_root: Path, destination: Path, *, check: bool) -> bool:
    desired = expected_content(module_root, destination)
    current = destination.read_text(encoding="utf-8") if destination.exists() else ""
    if current == desired:
        return False
    if current and not current.lstrip().startswith(MARKER):
        raise CompileError(f"refusing to overwrite hand-authored file: {destination}")
    if check:
        return True
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(destination.suffix + ".tmp")
    temporary.write_text(desired, encoding="utf-8")
    os.replace(temporary, destination)
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=Path.home(), type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    root = args.root.expanduser().resolve()
    module_root = root / ".apm" / "apm_modules"
    destinations = [root / ".claude" / "CLAUDE.md", root / ".codex" / "AGENTS.md"]
    try:
        changed = [
            path for path in destinations if sync_file(module_root, path, check=args.check)
        ]
    except (CompileError, OSError, yaml.YAMLError) as exc:
        print(f"global context compilation failed: {exc}", file=sys.stderr)
        return 1
    state = "need compilation" if args.check else "compiled"
    print(f"Global root contexts: {len(changed)} {state}; {len(destinations) - len(changed)} current")
    return 1 if args.check and changed else 0


if __name__ == "__main__":
    raise SystemExit(main())
