#!/usr/bin/env python3
"""Write minimal CLAUDE.md pointers beside compiled AGENTS.md files."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".apm",
    ".agents",
    ".claude",
    ".codex",
    ".cursor",
    ".github",
    ".venv",
    "__pycache__",
    "apm_modules",
    "dist",
    "node_modules",
    "target",
    "vendor",
}

CONTENT = """# DO NOT WRITE THIS FILE

@AGENTS.md

This file is generated by the project-local APM setup so Claude Code follows
the same progressive-disclosure index as Codex.
"""


def find_agents_files(root: Path) -> list[Path]:
    agents_files: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(name for name in dirnames if name not in SKIP_DIRS)
        if "AGENTS.md" in filenames:
            agents_files.append(Path(dirpath) / "AGENTS.md")
    return sorted(agents_files)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Write a minimal CLAUDE.md pointer beside each AGENTS.md file."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Project root to scan. Defaults to the current directory.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print files that would be written without modifying them.",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    written = 0

    for agents_path in find_agents_files(root):
        claude_path = agents_path.with_name("CLAUDE.md")
        if args.dry_run:
            print(f"would write {claude_path.relative_to(root)}")
            continue
        claude_path.write_text(CONTENT, encoding="utf-8")
        written += 1
        print(f"wrote {claude_path.relative_to(root)}")

    if not args.dry_run:
        print(f"wrote {written} CLAUDE.md pointer file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
