"""Coverage for the two quality advisories and the module they share.

Both hooks are advisory by design, so every case asserts exit 0 and that no
denial is ever produced. What varies is whether anything is said at all, and most
of these tests pin the cases where the answer is nothing: an unrecognised project,
a repository where pre-commit already owns the checks, an edit below the
thresholds. A hook that speaks on every call is one the agent learns to skip.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parent.parent / "scripts"
BEFORE_COMMIT = SCRIPTS / "quality-before-commit.py"
EDIT_ADVISORY = SCRIPTS / "quality-edit-advisory.py"

sys.path.insert(0, str(SCRIPTS))

import quality_common  # noqa: E402


def git(repo: Path, *args: str) -> None:
    subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
        env={
            "GIT_CONFIG_GLOBAL": "/dev/null",
            "GIT_CONFIG_SYSTEM": "/dev/null",
            "HOME": str(repo),
            "PATH": "/usr/bin:/bin:/usr/local/bin:/opt/homebrew/bin",
        },
    )


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    work = tmp_path / "repo"
    work.mkdir()
    git(work, "init", "-q")
    return work


def invoke(script: Path, payload: dict, cwd: Path, env: dict | None = None) -> tuple[int, dict | None]:
    import os

    # The hook itself must not inherit the host's system git config: on a machine
    # where a corporate wrapper sets core.hooksPath, `git rev-parse --git-path
    # hooks` resolves outside the fixture and the pre-commit deferral check
    # correctly declines to fire, which would look like a hook bug.
    environment = {
        **os.environ,
        "TMPDIR": str(cwd / ".state"),
        "GIT_CONFIG_SYSTEM": "/dev/null",
        "GIT_CONFIG_GLOBAL": "/dev/null",
    }
    (cwd / ".state").mkdir(exist_ok=True)
    if env:
        environment.update(env)
    result = subprocess.run(
        [sys.executable, str(script)],
        input=json.dumps(payload),
        capture_output=True,
        text=True,
        cwd=cwd,
        env=environment,
        timeout=120,
    )
    decision = json.loads(result.stdout)["hookSpecificOutput"] if result.stdout.strip() else None
    return result.returncode, decision


def commit_payload(repo: Path, message: str = "wip") -> dict:
    return {"cwd": str(repo), "tool_name": "Bash", "tool_input": {"command": f'git commit -m "{message}"'}}


# --- quality-before-commit ----------------------------------------------------


def test_unrecognised_project_says_nothing(repo: Path) -> None:
    """No marker file and no declared language means no basis for advice."""
    code, decision = invoke(BEFORE_COMMIT, commit_payload(repo), repo)
    assert code == 0
    assert decision is None


def test_misformatted_go_is_reported(repo: Path) -> None:
    import shutil

    if not shutil.which("gofmt"):
        pytest.skip("gofmt is not installed")
    (repo / "go.mod").write_text("module x\n\ngo 1.21\n")
    (repo / "bad.go").write_text("package x\nfunc  F(){}\n")
    git(repo, "add", "-A")
    code, decision = invoke(BEFORE_COMMIT, commit_payload(repo), repo)
    assert code == 0
    assert decision is not None
    assert decision["permissionDecision"] == "allow"
    assert "gofmt" in decision["additionalContext"]


def test_skip_lint_marker_suppresses_everything(repo: Path) -> None:
    (repo / "go.mod").write_text("module x\n\ngo 1.21\n")
    (repo / "bad.go").write_text("package x\nfunc  F(){}\n")
    git(repo, "add", "-A")
    code, decision = invoke(BEFORE_COMMIT, commit_payload(repo, "wip [skip lint]"), repo)
    assert code == 0
    assert decision is None


def test_defers_when_precommit_owns_the_checks(repo: Path) -> None:
    """Re-running the same formatters would be duplicate work and a duplicate nag."""
    (repo / "go.mod").write_text("module x\n\ngo 1.21\n")
    (repo / "bad.go").write_text("package x\nfunc  F(){}\n")
    (repo / ".pre-commit-config.yaml").write_text("repos: []\n")
    hooks = repo / ".git" / "hooks"
    hooks.mkdir(parents=True, exist_ok=True)
    hook = hooks / "pre-commit"
    hook.write_text("#!/bin/sh\n# File generated by pre-commit: https://pre-commit.com\n")
    hook.chmod(0o755)
    git(repo, "add", "-A")
    code, decision = invoke(BEFORE_COMMIT, commit_payload(repo), repo)
    assert code == 0
    assert decision is None


def test_still_advises_when_the_framework_hook_is_absent(repo: Path) -> None:
    """A config alone proves nothing: nobody may have run the install."""
    import shutil

    if not shutil.which("gofmt"):
        pytest.skip("gofmt is not installed")
    (repo / "go.mod").write_text("module x\n\ngo 1.21\n")
    (repo / "bad.go").write_text("package x\nfunc  F(){}\n")
    (repo / ".pre-commit-config.yaml").write_text("repos: []\n")
    git(repo, "add", "-A")
    _, decision = invoke(BEFORE_COMMIT, commit_payload(repo), repo)
    assert decision is not None


@pytest.mark.parametrize(
    "command",
    [
        pytest.param("git status", id="status"),
        pytest.param("git log --grep commit", id="log-mentioning-commit"),
        pytest.param("echo commit", id="not-git"),
    ],
)
def test_non_commit_commands_are_ignored(command: str, repo: Path) -> None:
    (repo / "go.mod").write_text("module x\n\ngo 1.21\n")
    payload = {"cwd": str(repo), "tool_name": "Bash", "tool_input": {"command": command}}
    code, decision = invoke(BEFORE_COMMIT, payload, repo)
    assert code == 0
    assert decision is None


def test_never_denies(repo: Path) -> None:
    """Every finding here is a formatting nit, so blocking would cost more."""
    (repo / "go.mod").write_text("module x\n\ngo 1.21\n")
    (repo / "bad.go").write_text("package x\nfunc  F(){}\n")
    git(repo, "add", "-A")
    _, decision = invoke(BEFORE_COMMIT, commit_payload(repo), repo)
    if decision is not None:
        assert decision["permissionDecision"] == "allow"


# --- quality-edit-advisory ----------------------------------------------------


def test_single_small_edit_stays_below_the_threshold(repo: Path) -> None:
    (repo / "go.mod").write_text("module x\n\ngo 1.21\n")
    payload = {"cwd": str(repo), "tool_name": "Edit", "tool_input": {"file_path": "a.go", "new_string": "x\n"}}
    code, decision = invoke(EDIT_ADVISORY, payload, repo)
    assert code == 0
    assert decision is None


def test_codex_patch_payload_is_recognised(repo: Path) -> None:
    """Codex sends the whole patch in tool_input.command rather than a file path."""
    (repo / "go.mod").write_text("module x\n\ngo 1.21\n")
    patch = "*** Update File: x.go\n@@\n-package x\n+package changed\n"
    payload = {"cwd": str(repo), "tool_name": "apply_patch", "tool_input": {"command": patch}}
    code, decision = invoke(
        EDIT_ADVISORY,
        payload,
        repo,
        env={
            "AGENTIC_QUALITY_LANGS": "go",
            "AGENTIC_QUALITY_ADVISORY_LINES": "1",
            "AGENTIC_QUALITY_ADVISORY_COOLDOWN_SECONDS": "0",
        },
    )
    assert code == 0
    assert decision is not None
    assert "QUALITY ADVISORY" in decision["additionalContext"]


def test_advisory_only_names_languages_present_in_the_edits(repo: Path) -> None:
    """A Python-only change must never suggest cargo."""
    (repo / "pyproject.toml").write_text("[project]\nname='x'\n")
    payload = {"cwd": str(repo), "tool_name": "Edit", "tool_input": {"file_path": "a.py", "new_string": "x\n" * 200}}
    _, decision = invoke(
        EDIT_ADVISORY,
        payload,
        repo,
        env={
            "AGENTIC_QUALITY_LANGS": "all",
            "AGENTIC_QUALITY_ADVISORY_LINES": "1",
            "AGENTIC_QUALITY_ADVISORY_COOLDOWN_SECONDS": "0",
        },
    )
    assert decision is not None
    context = decision["additionalContext"]
    assert "ruff" in context
    assert "cargo" not in context


def test_cooldown_suppresses_a_second_advisory(repo: Path) -> None:
    (repo / "pyproject.toml").write_text("[project]\nname='x'\n")
    payload = {"cwd": str(repo), "tool_name": "Edit", "tool_input": {"file_path": "a.py", "new_string": "x\n" * 200}}
    env = {
        "AGENTIC_QUALITY_LANGS": "python",
        "AGENTIC_QUALITY_ADVISORY_LINES": "1",
        "AGENTIC_QUALITY_ADVISORY_COOLDOWN_SECONDS": "3600",
    }
    _, first = invoke(EDIT_ADVISORY, payload, repo, env=env)
    assert first is not None
    _, second = invoke(EDIT_ADVISORY, payload, repo, env=env)
    assert second is None, "a second advisory inside the cooldown is a nag"


# --- both hooks fail open ----------------------------------------------------


@pytest.mark.parametrize("script", [BEFORE_COMMIT, EDIT_ADVISORY], ids=["before-commit", "edit-advisory"])
@pytest.mark.parametrize(
    "payload",
    [
        pytest.param("", id="empty"),
        pytest.param("not json", id="malformed"),
        pytest.param('{"tool_input": 42}', id="wrong-type"),
        pytest.param('{"tool_input": {"file_path": null}}', id="null-field"),
    ],
)
def test_unreadable_payload_fails_open(script: Path, payload: str, tmp_path: Path) -> None:
    result = subprocess.run(
        [sys.executable, str(script)],
        input=payload,
        capture_output=True,
        text=True,
        cwd=tmp_path,
        timeout=30,
    )
    assert result.returncode == 0
    assert not result.stdout.strip()


# --- the shared module -------------------------------------------------------


def test_selection_file_wins_over_marker_detection(tmp_path: Path) -> None:
    """An explicit selection lets a polyglot repo opt in per language."""
    (tmp_path / "go.mod").write_text("module x\n")
    (tmp_path / ".agents/hooks").mkdir(parents=True)
    (tmp_path / ".agents/hooks/quality-languages").write_text("python, rust\n")
    assert quality_common.selected_languages(tmp_path) == {"python", "rust"}


def test_markers_detect_languages_when_nothing_is_declared(tmp_path: Path) -> None:
    (tmp_path / "go.mod").write_text("module x\n")
    (tmp_path / "Cargo.toml").write_text("[package]\n")
    assert quality_common.selected_languages(tmp_path) == {"go", "rust"}


@pytest.mark.parametrize(
    ("path", "expected"),
    [
        ("a.go", "go"),
        ("a.py", "python"),
        ("a.pyi", "python"),
        ("a.rs", "rust"),
        ("Cargo.toml", "rust"),
        ("a.tsx", "ts"),
        ("a.mjs", "ts"),
        ("README.md", None),
        ("Makefile", None),
    ],
)
def test_language_for_file(path: str, expected: str | None) -> None:
    assert quality_common.language_for_file(path) == expected


def test_ts_answers_for_its_aliases() -> None:
    """A repo declaring `typescript` or `javascript` still enables the ts checks."""
    assert quality_common.language_enabled("ts", {"typescript"})
    assert quality_common.language_enabled("ts", {"javascript"})
    assert quality_common.language_enabled("rust", {"all"})
    assert not quality_common.language_enabled("rust", {"python"})
