#!/usr/bin/env bash
set -euo pipefail

input="$(cat)"
command="$(printf '%s' "$input" | jq -r '.tool_input.command // empty' 2>/dev/null || true)"

if printf '%s' "$command" | grep -iEq "co-authored-by.*(claude|anthropic|noreply@anthropic)|generated.by.*(claude|ai)|AI.assisted|AI.generated"; then
  echo "BLOCKED: Commit contains AI attribution. Remove Co-Authored-By, 'generated by', or AI mentions. The user is the sole author." >&2
  exit 2
fi

exit 0
