#!/usr/bin/env bash
set -euo pipefail

# attribution-guard.sh
#
# PreToolUse hook (Claude + Codex). Warns when `git commit` invocations carry
# AI authorship attribution -- Co-Authored-By trailers pointing at
# Claude/Anthropic, "Generated with ..." trailers, or AI-assisted/AI-generated
# phrasing -- so that the human stays the sole author of record.
#
# Non-blocking model: emits allow+additionalContext JSON on stdout (exit 0).
# Claude surfaces the advisory to the model; Codex treats exit 0 as allow.
#
# Portability floor: bash 3.2.57 + BSD grep. No PCRE, no \b. Case-insensitive
# matching via grep -i; structure-only matching via tr-lowercasing where needed.

payload="$(cat 2>/dev/null || true)"

# No jq -> we cannot parse the payload safely, so do not block (fail open: this
# is an authorship-hygiene guard, not a security control).
command -v jq >/dev/null 2>&1 || exit 0

# Cheap pre-jq bail: this guard acts ONLY on `git commit` commands, so if the raw
# payload contains no `commit` token there is nothing to inspect. Skips the jq
# spawn (the dominant per-call cost) for the common case on the hot path. Pure
# SUPERSET filter on literal bytes — the command still has to survive the
# structured checks below — so it can never mask a command jq would have flagged.
case "$payload" in
  *commit*) ;;
  *) exit 0 ;;
esac

# String-form tool_input idiom: tool_input may be an object {command: "..."} or
# a bare string. The naive '.tool_input.command // .tool_input' THROWS when
# tool_input is a string, which silently bypasses the guard. Type-check first.
command="$(
  printf '%s' "$payload" | jq -r '
    if (.tool_input|type)=="string" then .tool_input
    else (.tool_input.command // empty) end
  ' 2>/dev/null || true
)"

if [ -z "$command" ] || [ "$command" = "null" ]; then
  exit 0
fi

# Warn: emit an allow+additionalContext JSON on stdout (non-blocking advisory).
# $1 = short description of what was detected, woven into the message.
block() {
  warn_msg="this git commit carries AI authorship attribution ($1). The human is the sole author of record — drop any 'Co-Authored-By: Claude/...' trailer, 'Generated with/by Claude/AI' lines, Claude Code trailer URLs, and 'AI-assisted/AI-generated' qualifiers, then re-commit with a clean message. Proceeding."
  jq -cn --arg ctx "$warn_msg" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"allow",additionalContext:$ctx}}' 2>/dev/null || true
  exit 0
}

# Anchor to an actual `git commit`. This must fire for `git commit ...` and for
# `git -C <path> commit ...` / `git --git-dir=... commit ...`, but NOT for other
# git subcommands (log, show, rebase) or arbitrary Bash that merely contains the
# word "commit". The middle group `([[:space:]][^;&|]*)?` allows global git
# options between `git` and `commit` while staying within one command segment.
if ! printf '%s' "$command" | grep -Eq '(^|[[:space:]])git([[:space:]][^;&|]*)?[[:space:]]+commit($|[[:space:]])'; then
  exit 0
fi

# --- attribution detection -------------------------------------------------
#
# These patterns are deliberately scoped to ATTRIBUTION constructs, not to any
# mention of "AI" or "Claude" in prose. A commit body like
#   "fix AI model loading bug" or "refactor claude client wrapper"
# must NOT trip the guard. We therefore require attribution-shaped context:
#   - a Co-Authored-By: trailer naming an AI agent / its noreply address
#   - a "Generated with/by ..." phrase naming an AI agent
#   - the hyphenated qualifiers "AI-assisted" / "AI-generated" (an authorship
#     claim), but NOT a bare "AI" token
#   - the Claude Code default trailer URL
#
# Each pattern is matched case-insensitively (grep -i).

# 1. Co-Authored-By trailer naming Claude / Anthropic / Anthropic's noreply.
#    Tolerates "Co-Authored-By" and "Co-authored-by" plus arbitrary spacing.
trailer_pat='co-authored-by[[:space:]]*:.*(claude|anthropic|noreply@anthropic)'

# 2. "Generated with" / "Generated by" naming Claude / an AI agent.
#    Matches "Generated with Claude Code", "generated by claude", "generated by
#    AI", "co-created with claude". The "ai" alternative is bounded by a
#    non-word edge below via the separate ai_attr_pat; here it must follow
#    "generated (with|by)" which is already attribution context.
generated_pat='generat(ed|ing)[[:space:]]+(with|by)[[:space:]]+(claude|anthropic|ai($|[^a-z])|a model|an? (llm|language model))'

# 3. Authorship-qualifier phrases: the HYPHENATED forms "AI-assisted",
#    "AI-generated", "AI-authored", "AI-written" — these are authorship claims.
#    Deliberately NARROW:
#      - hyphen ONLY (no space form): "AI generated thumbnails" / "AI assisted
#        diagnosis" are FEATURE descriptions, not commit attribution, so the
#        space-separated form is allowed.
#      - excludes "coded"/"created": "AI-coded"/"AI-created" appear far more as
#        product/feature names than as authorship trailers. The high-signal
#        authorship verbs (assisted|generated|authored|written) are kept.
ai_attr_pat='ai-(assisted|generated|authored|written)'

# 4. Claude Code's default trailer URL (appears even when the agent omits the
#    Co-Authored-By line).
url_pat='claude\.com/claude-code|claude\.ai/code'

# 5. Robot emoji + Claude marker is the canonical Claude Code signature line.
#    The emoji alone is not attribution; require the Claude marker nearby. We
#    fold this into generated_pat / url_pat above, so the bare emoji is allowed.

if printf '%s' "$command" | grep -iEq "$trailer_pat"; then
  block "Co-Authored-By trailer naming Claude/Anthropic"
elif printf '%s' "$command" | grep -iEq "$generated_pat"; then
  block "a \"Generated with/by ...\" attribution"
elif printf '%s' "$command" | grep -iEq "$ai_attr_pat"; then
  block "an \"AI-assisted/AI-generated\" authorship qualifier"
elif printf '%s' "$command" | grep -iEq "$url_pat"; then
  block "a Claude Code trailer URL"
fi

exit 0
