#!/usr/bin/env bats
#
# Coverage for the attribution guard. Asserts that AI authorship attribution in
# a `git commit` command triggers a non-blocking advisory (exit 0,
# permissionDecision:"allow" + additionalContext on stdout), that clean commits
# and prose that merely mentions AI/Claude are allowed silently (exit 0, no
# output), that non-commit git commands are ignored, and that the string-form
# tool_input payload is handled (does not bypass the guard). Also asserts the
# script PARSES under /bin/bash (macOS bash 3.2.57).
#
# Run: bats packages/hooks-attribution-guard/tests/attribution-guard.bats

setup() {
  GUARD="${BATS_TEST_DIRNAME}/../scripts/attribution-guard.sh"
}

# --- helpers ---------------------------------------------------------------

# Object tool_input: {tool_input: {command: "..."}}.
mk_obj() {
  jq -cn --arg cmd "$1" '{tool_input: {command: $cmd}}'
}

# Bare-string tool_input: {tool_input: "..."} (the historical bypass shape).
mk_str() {
  jq -cn --arg cmd "$1" '{tool_input: $cmd}'
}

# Run the guard with a payload on stdin; capture exit status into $status and
# combined output into $output. The `|| true`-style guard on the assignment
# keeps a non-zero guard exit (the block path) from aborting the bats test
# before we record it.
run_guard() {
  payload="$1"
  output="$(printf '%s' "$payload" | /bin/bash "$GUARD" 2>&1)" && status=0 || status=$?
}

# --- parse / portability floor --------------------------------------------

@test "attribution-guard.sh parses under /bin/bash (no bash-4 syntax)" {
  run /bin/bash -n "$GUARD"
  [ "$status" -eq 0 ]
}

# --- advisory: AI attribution in commit (allow + additionalContext on stdout)
# Non-blocking: always exit 0; the JSON on stdout carries permissionDecision
# "allow" and an additionalContext explaining what to remove.

@test "Co-Authored-By: Claude trailer -> advisory (exit 0, allow+additionalContext)" {
  run_guard "$(mk_obj 'git commit -m "feat: x" -m "Co-Authored-By: Claude <noreply@anthropic.com>"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "Co-authored-by anthropic noreply -> advisory (exit 0)" {
  run_guard "$(mk_obj 'git commit -m "x" -m "Co-authored-by: someone <noreply@anthropic.com>"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "robot emoji + Generated with Claude Code -> advisory (exit 0)" {
  run_guard "$(mk_obj 'git commit -m "fix: y" -m "🤖 Generated with Claude Code"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "generated by AI -> advisory (exit 0)" {
  run_guard "$(mk_obj 'git commit -m "feature generated by AI"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "AI-assisted authorship qualifier -> advisory (exit 0)" {
  run_guard "$(mk_obj 'git commit -m "AI-assisted refactor"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "AI-generated authorship qualifier -> advisory (exit 0)" {
  run_guard "$(mk_obj 'git commit -m "AI-generated test scaffolding"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "Claude Code trailer URL -> advisory (exit 0)" {
  run_guard "$(mk_obj 'git commit -m "x https://claude.com/claude-code"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "git -C <path> commit with attribution -> advisory (exit 0)" {
  run_guard "$(mk_obj 'git -C /tmp/repo commit -m "Co-Authored-By: claude"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "advisory message names what to remove (additionalContext)" {
  run_guard "$(mk_obj 'git commit -m "Co-Authored-By: Claude"')"
  [ "$status" -eq 0 ]
  ctx="$(printf '%s' "$output" | jq -r '.hookSpecificOutput.additionalContext // empty')"
  [[ "$ctx" == *"Co-Authored-By"* ]]
  [[ "$ctx" == *"sole author"* ]]
}

# --- allow: clean commits --------------------------------------------------

@test "clean commit message -> allow (exit 0)" {
  run_guard "$(mk_obj 'git commit -m "fix: handle null input"')"
  [ "$status" -eq 0 ]
}

# --- allow: prose mentioning AI/Claude is NOT attribution (no false positive)

@test "commit body mentioning 'AI model' -> allow (no false positive)" {
  run_guard "$(mk_obj 'git commit -m "fix AI model loading bug"')"
  [ "$status" -eq 0 ]
}

@test "commit body mentioning 'claude client' -> allow (no false positive)" {
  run_guard "$(mk_obj 'git commit -m "refactor claude client wrapper"')"
  [ "$status" -eq 0 ]
}

@test "bare robot emoji without Claude marker -> allow (no false positive)" {
  run_guard "$(mk_obj 'git commit -m "🤖 automate the release pipeline"')"
  [ "$status" -eq 0 ]
}

# --- allow: AI/feature DESCRIPTIONS are not authorship attribution ----------
# Pattern 3 is hyphen-only and excludes coded/created, so these FEATURE names
# (describing the product, not who wrote the commit) must NOT be blocked.

@test "space-form 'AI generated thumbnails' feature -> allow (not hyphenated)" {
  run_guard "$(mk_obj 'git commit -m "add AI generated thumbnails to gallery"')"
  [ "$status" -eq 0 ]
}

@test "space-form 'AI assisted diagnosis' feature -> allow" {
  run_guard "$(mk_obj 'git commit -m "ship AI assisted diagnosis mode"')"
  [ "$status" -eq 0 ]
}

@test "'AI-coded' feature name -> allow (coded excluded from pattern)" {
  run_guard "$(mk_obj 'git commit -m "add AI-coded sample to docs"')"
  [ "$status" -eq 0 ]
}

@test "'AI-created' feature name -> allow (created excluded from pattern)" {
  run_guard "$(mk_obj 'git commit -m "render AI-created avatars"')"
  [ "$status" -eq 0 ]
}

# --- allow: non-commit git commands ----------------------------------------

@test "git log piping a 'generated by AI' string -> allow (not a commit)" {
  run_guard "$(mk_obj 'git log --oneline | grep -i "generated by AI"')"
  [ "$status" -eq 0 ]
}

@test "git show is ignored (not a commit)" {
  run_guard "$(mk_obj 'git show HEAD')"
  [ "$status" -eq 0 ]
}

# --- string-form payload ---------------------------------------------------

@test "string-form tool_input with attribution -> advisory (exit 0, allow+additionalContext)" {
  run_guard "$(mk_str 'git commit -m "Co-Authored-By: Claude"')"
  [ "$status" -eq 0 ]
  printf '%s' "$output" | jq -e '.hookSpecificOutput.permissionDecision == "allow"' >/dev/null
}

@test "string-form tool_input clean commit -> allow (exit 0)" {
  run_guard "$(mk_str 'git commit -m "fix: handle null input"')"
  [ "$status" -eq 0 ]
}

# --- malformed / empty stdin -----------------------------------------------

@test "empty stdin -> allow (exit 0)" {
  run_guard ""
  [ "$status" -eq 0 ]
}

@test "non-JSON stdin -> allow (exit 0)" {
  run_guard "not json at all"
  [ "$status" -eq 0 ]
}
