"""Coverage for the AI-attribution advisory guard.

The guard is a nudge, not a gate: every case must exit 0. What varies is whether
an advisory is emitted. The negative cases carry the weight here -- a guard that
fires on "fix AI model loading bug" would be worse than no guard, so ordinary
work mentioning an agent or a model must pass untouched.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

GUARD = Path(__file__).resolve().parent.parent / "scripts" / "attribution-guard.py"


def run_guard(command: str, *, as_string: bool = False) -> tuple[int, dict | None]:
    """Run the guard on one command; return its exit code and decision object."""
    tool_input = command if as_string else {"command": command}
    payload = json.dumps(
        {"cwd": ".", "tool_name": "Bash", "tool_input": tool_input}
    )
    result = subprocess.run(
        [sys.executable, str(GUARD)],
        input=payload,
        capture_output=True,
        text=True,
        timeout=30,
    )
    decision = json.loads(result.stdout)["hookSpecificOutput"] if result.stdout.strip() else None
    return result.returncode, decision


def commit(message: str) -> str:
    """Build the `git commit` command an agent would actually issue.

    The message is interpolated rather than passed through json.dumps: that would
    escape a non-ASCII character to a \\uXXXX pair, which no real payload
    contains, and the emoji-signature cases would then be testing the escaping
    rather than the guard.
    """
    return f'git commit -m "{message}"'


# Attribution the guard must flag. Each entry is a real trailer or signature
# emitted by a shipping agent, not a hypothetical.
FLAGGED = [
    pytest.param("Co-Authored-By: Claude <noreply@anthropic.com>", id="claude-trailer"),
    pytest.param("Co-authored-by: claude <noreply@anthropic.com>", id="claude-lowercase"),
    pytest.param("Co-Authored-By: Cursor Agent <agent@cursor.sh>", id="cursor"),
    pytest.param("Co-Authored-By: GitHub Copilot <copilot@github.com>", id="copilot"),
    pytest.param("Co-Authored-By: Devin AI <devin@cognition.ai>", id="devin"),
    pytest.param("Co-Authored-By: aider <aider@aider.chat>", id="aider"),
    pytest.param("Co-Authored-By: Codex <codex@openai.com>", id="codex"),
    pytest.param("Co-Authored-By: gemini-cli <gemini@google.com>", id="gemini"),
    pytest.param("Co-authored-by: openhands <openhands@all-hands.dev>", id="openhands"),
    pytest.param("Co-Authored-By: Windsurf <agent@codeium.com>", id="windsurf"),
    pytest.param("Assisted-by: Claude", id="assisted-by-trailer"),
    pytest.param("Signed-off-by: Claude <noreply@anthropic.com>", id="signed-off-by"),
    pytest.param("Generated with Claude Code", id="generated-with-claude"),
    pytest.param("Generated with Cursor", id="generated-with-cursor"),
    pytest.param("Generated by GPT-4", id="generated-by-gpt"),
    pytest.param("Generated with Codex CLI", id="generated-with-codex"),
    pytest.param("feature generated by AI", id="generated-by-bare-ai"),
    pytest.param("Written by an AI agent", id="written-by-agent"),
    pytest.param("AI-assisted refactor", id="ai-assisted"),
    pytest.param("AI-generated helper", id="ai-generated"),
    pytest.param("llm-generated helper", id="llm-generated"),
    pytest.param("see https://claude.com/claude-code", id="claude-url"),
    pytest.param("\U0001f916 Generated with Cursor", id="robot-emoji-signature"),
    # A full agent-shaped commit: subject, emoji signature, and trailer.
    pytest.param(
        "feat: x\n\n\U0001f916 Generated with Claude Code\n\n"
        "Co-Authored-By: Claude <noreply@anthropic.com>",
        id="full-agent-commit",
    ),
    pytest.param("feat: x\n\nAI-generated", id="qualifier-on-its-own-line"),
]

# Ordinary work that names an agent, a model, or AI as subject matter. None of
# this claims authorship, so none of it may be flagged.
CLEAN = [
    pytest.param("fix AI model loading bug", id="ai-as-subject"),
    pytest.param("refactor claude client wrapper", id="claude-as-library"),
    pytest.param("add AI generated thumbnails feature", id="space-form-feature"),
    pytest.param("feat: AI-powered search ranking", id="ai-powered-product"),
    pytest.param("feat: add an AI-coded badge to the UI", id="ai-coded-excluded"),
    pytest.param("docs: describe the copilot integration surface", id="copilot-as-topic"),
    pytest.param("fix: handle gpt-4 rate limits in the client", id="model-as-topic"),
    pytest.param("test: cover the cursor pagination helper", id="cursor-the-noun"),
    pytest.param("chore: bump anthropic sdk to 0.40", id="vendor-sdk-bump"),
    pytest.param("feat: aiohttp connection pooling", id="ai-prefix-word"),
    pytest.param("fix: airbnb style lint rules", id="ai-prefix-word-2"),
    pytest.param("docs: mention Codex CLI in the readme", id="agent-as-topic"),
    # Talking ABOUT attribution is not attribution. This guard's own commits and
    # docs quote these phrases, and an early version flagged them, so the cases
    # are pinned here.
    pytest.param(
        "docs: explain that Generated with Claude Code trailers are banned",
        id="prose-quoting-a-signature",
    ),
    pytest.param(
        "fix: the guard missed commits generated with Cursor, so widen it",
        id="prose-describing-a-gap",
    ),
    pytest.param(
        "docs: note that AI-assisted qualifiers are rejected by the guard",
        id="prose-quoting-a-qualifier",
    ),
]


@pytest.mark.parametrize("message", FLAGGED)
def test_attribution_is_flagged(message: str) -> None:
    code, decision = run_guard(commit(message))
    assert code == 0, "the guard must never block a commit"
    assert decision is not None, f"expected an advisory for: {message}"
    assert decision["permissionDecision"] == "allow"
    assert "additionalContext" in decision


@pytest.mark.parametrize("message", CLEAN)
def test_ordinary_work_is_not_flagged(message: str) -> None:
    code, decision = run_guard(commit(message))
    assert code == 0
    assert decision is None, f"false positive on: {message}"


def test_advisory_names_what_to_remove() -> None:
    _, decision = run_guard(commit("Co-Authored-By: Claude <noreply@anthropic.com>"))
    assert decision is not None
    context = decision["additionalContext"]
    assert "sole author of record" in context
    assert "re-commit" in context


def test_git_with_global_options_still_fires() -> None:
    command = (
        "git -C /tmp/repo commit -m "
        + json.dumps("Co-Authored-By: Claude <noreply@anthropic.com>")
    )
    _, decision = run_guard(command)
    assert decision is not None


@pytest.mark.parametrize(
    "command",
    [
        pytest.param("git log --grep 'generated by AI'", id="git-log"),
        pytest.param("git show HEAD", id="git-show"),
        pytest.param("echo 'Co-Authored-By: Claude'", id="not-a-git-command"),
    ],
)
def test_non_commit_commands_are_ignored(command: str) -> None:
    """Only a commit can carry attribution, so other commands must pass."""
    code, decision = run_guard(command)
    assert code == 0
    assert decision is None


def test_string_form_tool_input_is_read() -> None:
    """A bare-string tool_input must not silently bypass the guard."""
    _, decision = run_guard(
        commit("Co-Authored-By: Claude <noreply@anthropic.com>"), as_string=True
    )
    assert decision is not None


@pytest.mark.parametrize(
    "payload",
    [pytest.param("", id="empty"), pytest.param("not json at all", id="malformed")],
)
def test_unreadable_payload_fails_open(payload: str) -> None:
    result = subprocess.run(
        [sys.executable, str(GUARD)],
        input=payload,
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0
    assert not result.stdout.strip()

def test_one_undecodable_byte_does_not_silence_the_guard() -> None:
    """`sys.stdin.read()` raised UnicodeDecodeError and the fail-open swallowed it.

    So a single stray byte ANYWHERE in the payload turned a deny into silence -- even
    a byte in a field this guard never reads. Reproduced here before the fix: the
    valid payload denied, the same payload plus one bad byte decided nothing.

    Eleven guards across this repository shared the idiom; all now read bytes and
    decode with "replace".
    """
    attributed = (
        "git commit -m 'x\n\nCo-Authored-By: Claude <noreply@anthropic.com>'"
    )
    payload = json.dumps({"cwd": ".", "tool_name": "Bash", "tool_input": {"command": attributed}})
    poisoned = payload.encode()[:-1] + b', "unread_field":"scratch\xe9"}'

    clean = subprocess.run(  # noqa: S603
        [sys.executable, str(GUARD)], input=payload.encode(), capture_output=True, timeout=30
    )
    assert clean.stdout.strip(), "the valid payload must produce a decision"

    result = subprocess.run(  # noqa: S603
        [sys.executable, str(GUARD)], input=poisoned, capture_output=True, timeout=30
    )
    assert result.returncode == 0, "the guard must still fail open"
    assert result.stdout.strip(), "an undecodable byte erased the decision"
