#!/usr/bin/env bats
#
# Coverage for precommit-gate.sh — the PreToolUse hook that ensures the
# pre-commit framework is actually active when a repo opts into it.
#
# The hook reads a JSON event on stdin and either allows (exit 0, no output) or
# blocks (exit 2 + stderr). Fixtures are throwaway git repos in various states:
#   - no .pre-commit-config.yaml            -> always allow (silent)
#   - config + the relevant git hook present -> allow
#   - config + git hook MISSING              -> block
#   - --no-verify / -n                       -> block (skips the framework)
#
# Portability floor: bash 3.2.57 + BSD userland.
# Run: bats packages/hooks-precommit-gate/tests/precommit-gate.bats

setup() {
  # Hermetic git: ignore host system/global config (e.g. a corporate
  # core.hooksPath) so fixture commits are fast and deterministic. NOTE: tests
  # that assert on core.hooksPath set it explicitly per-fixture, which still wins.
  export GIT_CONFIG_SYSTEM=/dev/null GIT_CONFIG_GLOBAL=/dev/null
  GUARD="${BATS_TEST_DIRNAME}/../scripts/precommit-gate.sh"
  command -v jq  >/dev/null 2>&1 || skip "jq not available"
  command -v git >/dev/null 2>&1 || skip "git not available"
}

# new_repo <state> -> prints a fresh fixture repo path.
#   bare        git repo, NO .pre-commit-config.yaml
#   config      has .pre-commit-config.yaml, NO installed git hooks
#   installed   has config AND pre-commit-managed pre-commit + pre-push hooks
new_repo() {
  local state="$1" dir
  dir="$(mktemp -d "${BATS_TEST_TMPDIR}/repo.XXXXXX")"
  dir="$(cd "$dir" && pwd -P)"
  git -C "$dir" init -q
  # Pin core.hooksPath to THIS repo's own hooks dir, overriding any global
  # core.hooksPath the test machine may have (e.g. a corporate git wrapper),
  # which would otherwise make the guard fail open and the assertions moot.
  git -C "$dir" config core.hooksPath "$dir/.git/hooks"
  case "$state" in
    bare) ;;
    config|installed)
      printf 'repos: []\n' >"$dir/.pre-commit-config.yaml"
      ;;
  esac
  if [ "$state" = "installed" ]; then
    # The pre-commit FRAMEWORK writes a 'generated by pre-commit' marker comment.
    for h in pre-commit pre-push; do
      printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexit 0\n' >"$dir/.git/hooks/$h"
      chmod +x "$dir/.git/hooks/$h"
    done
  fi
  printf '%s' "$dir"
}

# payload <cwd> <command> -> JSON event with .cwd and an object tool_input.
payload() {
  jq -cn --arg cwd "$1" --arg cmd "$2" '{cwd:$cwd, tool_input:{command:$cmd}}'
}

# run_gate <payload> -> sets $status and $output (stderr+stdout).
run_gate() {
  output="$(printf '%s' "$1" | /bin/bash "$GUARD" 2>&1)" && status=0 || status=$?
}

# --- parse / portability floor ---------------------------------------------

@test "precommit-gate.sh parses under /bin/bash (no bash-4 syntax)" {
  run /bin/bash -n "$GUARD"
  [ "$status" -eq 0 ]
}

# --- silent in repos with NO pre-commit config -----------------------------

@test "no config: git commit -> allow (silent)" {
  local r; r="$(new_repo bare)"
  run_gate "$(payload "$r" 'git commit -m x')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "no config: git push -> allow (silent)" {
  local r; r="$(new_repo bare)"
  run_gate "$(payload "$r" 'git push origin main')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "no config: even --no-verify -> allow (nothing to enforce)" {
  local r; r="$(new_repo bare)"
  run_gate "$(payload "$r" 'git commit --no-verify -m x')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# --- config present + hook installed -> allow ------------------------------

@test "config + installed hooks: git commit -> allow" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git commit -m x')"
  [ "$status" -eq 0 ]
}

@test "config + installed hooks: git push -> allow" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git push origin main')"
  [ "$status" -eq 0 ]
}

# --- config present + hook MISSING -> block --------------------------------

@test "config, no installed hook: git commit -> block (exit 2)" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" 'git commit -m x')"
  [ "$status" -eq 2 ]
  [[ "$output" == *"pre-commit install"* ]]
}

@test "config, no installed hook: git push -> block (exit 2)" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" 'git push origin main')"
  [ "$status" -eq 2 ]
  [[ "$output" == *"pre-push"* ]]
}

# --- --no-verify / -n bypass -> block (even with hooks installed) ----------

@test "installed hooks but --no-verify: git commit -> block" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git commit --no-verify -m x')"
  [ "$status" -eq 2 ]
  [[ "$output" == *"no-verify"* ]]
}

@test "installed hooks but -n short flag: git commit -> block" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git commit -n -m x')"
  [ "$status" -eq 2 ]
}

@test "installed hooks but --no-verify: git push -> block" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git push --no-verify origin main')"
  [ "$status" -eq 2 ]
}

# --- not a commit/push git command -> allow --------------------------------

@test "config repo: git status is not gated -> allow" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" 'git status')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "config repo: 'git commit' inside a quoted arg of another command -> allow" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" 'echo "how to git commit properly"')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# --- fail-open / robustness ------------------------------------------------

@test "not a git repo: git commit -> allow (fail open)" {
  local d; d="$(mktemp -d "${BATS_TEST_TMPDIR}/notrepo.XXXXXX")"
  run_gate "$(payload "$d" 'git commit -m x')"
  [ "$status" -eq 0 ]
}

@test "git -C redirect to another repo -> allow (cannot trust cwd)" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" "git -C /elsewhere commit -m x")"
  [ "$status" -eq 0 ]
}

@test "external core.hooksPath (corporate wrapper) -> allow (fail open)" {
  # When core.hooksPath points outside the repo, a centralized hooks manager
  # owns the hooks; pre-commit's per-repo install does not apply normally and we
  # must not block. config present + missing local hook would otherwise block.
  local r ext; r="$(new_repo config)"
  ext="$(mktemp -d "${BATS_TEST_TMPDIR}/exthooks.XXXXXX")"
  git -C "$r" config core.hooksPath "$ext"
  run_gate "$(payload "$r" 'git commit -m x')"
  [ "$status" -eq 0 ]
}

@test "string-form tool_input is handled (config, missing hook -> block)" {
  local r; r="$(new_repo config)"
  run_gate "$(jq -cn --arg cwd "$r" --arg cmd 'git commit -m x' '{cwd:$cwd, tool_input:$cmd}')"
  [ "$status" -eq 2 ]
}

@test "empty stdin -> allow (exit 0)" {
  run_gate ""
  [ "$status" -eq 0 ]
}

@test "non-JSON stdin -> allow (exit 0)" {
  run_gate "not json at all {"
  [ "$status" -eq 0 ]
}
