#!/usr/bin/env bats
#
# Coverage for precommit-gate.sh — the PreToolUse hook that ensures the
# pre-commit framework is actually active when a repo opts into it.
#
# The hook is NON-BLOCKING: it reads a JSON event on stdin and either allows
# silently (exit 0, no output) or emits a single advisory JSON object with
# permissionDecision:"allow" + additionalContext (still exit 0). No exit 2
# remains. Fixtures are throwaway git repos in various states:
#   - no .pre-commit-config.yaml            -> always allow (silent)
#   - config + the relevant git hook present -> allow (silent)
#   - config + git hook MISSING              -> allow + advisory
#   - --no-verify / -n                       -> allow + advisory
#
# Portability floor: bash 3.2.57 + BSD userland.
# Run: bats packages/hooks-precommit-gate/tests/precommit-gate.bats

setup() {
  # Hermetic git: ignore host system/global config (e.g. a corporate
  # core.hooksPath) so fixture commits are fast and deterministic. NOTE: tests
  # that assert on core.hooksPath set it explicitly per-fixture, which still wins.
  export GIT_CONFIG_SYSTEM=/dev/null GIT_CONFIG_GLOBAL=/dev/null
  GUARD="${BATS_TEST_DIRNAME}/../scripts/precommit-gate.sh"
  command -v jq  >/dev/null 2>&1 || skip "jq not available"
  command -v git >/dev/null 2>&1 || skip "git not available"
}

# new_repo <state> -> prints a fresh fixture repo path.
#   bare        git repo, NO .pre-commit-config.yaml
#   config      has .pre-commit-config.yaml, NO installed git hooks
#   installed   has config AND pre-commit-managed pre-commit + pre-push hooks
new_repo() {
  local state="$1" dir
  dir="$(mktemp -d "${BATS_TEST_TMPDIR}/repo.XXXXXX")"
  dir="$(cd "$dir" && pwd -P)"
  git -C "$dir" init -q
  # Pin core.hooksPath to THIS repo's own hooks dir, overriding any global
  # core.hooksPath the test machine may have (e.g. a corporate git wrapper),
  # which would otherwise make the guard fail open and the assertions moot.
  git -C "$dir" config core.hooksPath "$dir/.git/hooks"
  case "$state" in
    bare) ;;
    config|installed)
      printf 'repos: []\n' >"$dir/.pre-commit-config.yaml"
      ;;
  esac
  if [ "$state" = "installed" ]; then
    # The pre-commit FRAMEWORK writes a 'generated by pre-commit' marker comment.
    for h in pre-commit pre-push; do
      printf '#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\nexit 0\n' >"$dir/.git/hooks/$h"
      chmod +x "$dir/.git/hooks/$h"
    done
  fi
  printf '%s' "$dir"
}

# payload <cwd> <command> -> JSON event with .cwd and an object tool_input.
payload() {
  jq -cn --arg cwd "$1" --arg cmd "$2" '{cwd:$cwd, tool_input:{command:$cmd}}'
}

# run_gate <payload> -> sets $status, $output, $decision, $ctx.
# decision == "allow" + non-empty $ctx means advisory fired.
# Empty $output / empty $decision means silent allow.
run_gate() {
  output="$(printf '%s' "$1" | /bin/bash "$GUARD" 2>&1)" && status=0 || status=$?
  decision="$(printf '%s' "$output" | jq -r '.hookSpecificOutput.permissionDecision // empty' 2>/dev/null || true)"
  ctx="$(printf '%s' "$output" | jq -r '.hookSpecificOutput.additionalContext // empty' 2>/dev/null || true)"
}

# --- parse / portability floor ---------------------------------------------

@test "precommit-gate.sh parses under /bin/bash (no bash-4 syntax)" {
  run /bin/bash -n "$GUARD"
  [ "$status" -eq 0 ]
}

# --- silent in repos with NO pre-commit config -----------------------------

@test "no config: git commit -> allow (silent)" {
  local r; r="$(new_repo bare)"
  run_gate "$(payload "$r" 'git commit -m x')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "no config: git push -> allow (silent)" {
  local r; r="$(new_repo bare)"
  run_gate "$(payload "$r" 'git push origin main')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "no config: even --no-verify -> allow (nothing to enforce)" {
  local r; r="$(new_repo bare)"
  run_gate "$(payload "$r" 'git commit --no-verify -m x')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# --- config present + hook installed -> silent allow -----------------------

@test "config + installed hooks: git commit -> allow (silent)" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git commit -m x')"
  [ "$status" -eq 0 ]
  [ -z "$decision" ]
}

@test "config + installed hooks: git push -> allow (silent)" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git push origin main')"
  [ "$status" -eq 0 ]
  [ -z "$decision" ]
}

# --- config present + hook MISSING -> advisory (allow + additionalContext) -

@test "config, no installed hook: git commit -> advisory allow" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" 'git commit -m x')"
  [ "$status" -eq 0 ]
  [ "$decision" = "allow" ]
  [[ "$ctx" == *"pre-commit install"* ]]
}

@test "config, no installed hook: git push -> advisory allow" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" 'git push origin main')"
  [ "$status" -eq 0 ]
  [ "$decision" = "allow" ]
  [[ "$ctx" == *"pre-push"* ]]
}

# --- --no-verify / -n bypass -> advisory (allow + additionalContext) -------

@test "installed hooks but --no-verify: git commit -> advisory allow" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git commit --no-verify -m x')"
  [ "$status" -eq 0 ]
  [ "$decision" = "allow" ]
  [[ "$ctx" == *"no-verify"* ]]
}

@test "installed hooks but -n short flag: git commit -> advisory allow" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git commit -n -m x')"
  [ "$status" -eq 0 ]
  [ "$decision" = "allow" ]
  [ -n "$ctx" ]
}

@test "installed hooks but --no-verify: git push -> advisory allow" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" 'git push --no-verify origin main')"
  [ "$status" -eq 0 ]
  [ "$decision" = "allow" ]
  [ -n "$ctx" ]
}

# --- false-positive regression: rg -n in piped command ---------------------
# `git commit -m x && rg -n '^- [ ] T014' file`: the -n belongs to rg, not to
# git commit. The hook must emit an advisory (missing hook) but must NOT mention
# --no-verify in the advisory text.

@test "git commit && rg -n: advisory fires for missing hook, NOT for no-verify" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" "git commit -m x && rg -n '^- [ ] T014' file")"
  [ "$status" -eq 0 ]
  [ "$decision" = "allow" ]
  # Advisory should mention missing hook, not --no-verify
  [[ "$ctx" == *"pre-commit hook is not installed"* ]]
  [[ "$ctx" != *"no-verify"* ]]
}

# --- not a commit/push git command -> allow --------------------------------

@test "config repo: git status is not gated -> allow" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" 'git status')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

@test "config repo: 'git commit' inside a quoted arg of another command -> allow" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" 'echo "how to git commit properly"')"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}

# --- fail-open / robustness ------------------------------------------------

@test "not a git repo: git commit -> allow (fail open)" {
  local d; d="$(mktemp -d "${BATS_TEST_TMPDIR}/notrepo.XXXXXX")"
  run_gate "$(payload "$d" 'git commit -m x')"
  [ "$status" -eq 0 ]
}

@test "git -C redirect to another repo -> allow (cannot trust cwd)" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" "git -C /elsewhere commit -m x")"
  [ "$status" -eq 0 ]
}

@test "external core.hooksPath (corporate wrapper) -> allow (fail open)" {
  # When core.hooksPath points outside the repo, a centralized hooks manager
  # owns the hooks; pre-commit's per-repo install does not apply normally and we
  # must not block. config present + missing local hook would otherwise advise.
  local r ext; r="$(new_repo config)"
  ext="$(mktemp -d "${BATS_TEST_TMPDIR}/exthooks.XXXXXX")"
  git -C "$r" config core.hooksPath "$ext"
  run_gate "$(payload "$r" 'git commit -m x')"
  [ "$status" -eq 0 ]
}

@test "string-form tool_input is handled (config, missing hook -> advisory allow)" {
  local r; r="$(new_repo config)"
  run_gate "$(jq -cn --arg cwd "$r" --arg cmd 'git commit -m x' '{cwd:$cwd, tool_input:$cmd}')"
  [ "$status" -eq 0 ]
  [ "$decision" = "allow" ]
  [ -n "$ctx" ]
}

@test "empty stdin -> allow (exit 0)" {
  run_gate ""
  [ "$status" -eq 0 ]
}

@test "non-JSON stdin -> allow (exit 0)" {
  run_gate "not json at all {"
  [ "$status" -eq 0 ]
}

# --- issue #4: -C inside a commit message -> must NOT fail-open --------------
# A literal ' -C ' inside the -m value should not trigger the redirect guard.

@test "-C inside commit message -> advisory for missing hook, not fail-open (issue #4)" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" "git commit -m 'change dir with -C flag'")"
  [ "$status" -eq 0 ]
  # Must advise about the missing hook, not silently fail-open.
  [ "$decision" = "allow" ]
  [[ "$ctx" == *"not installed"* ]]
}

@test "--git-dir inside commit message -> advisory, not fail-open (issue #4)" {
  local r; r="$(new_repo config)"
  run_gate "$(payload "$r" "git commit -m 'use --git-dir option'")"
  [ "$status" -eq 0 ]
  [ "$decision" = "allow" ]
  [[ "$ctx" == *"not installed"* ]]
}

# --- issue #5: --no-verify / -n only in commit message -> no false positive --

@test "--no-verify only in commit message -> silent (issue #5)" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" "git commit -m 'add --no-verify support'")"
  [ "$status" -eq 0 ]
  # hooks are installed, --no-verify is only in the message -> completely silent
  [ -z "$output" ]
}

@test "-n only in commit message -> silent (issue #5)" {
  local r; r="$(new_repo installed)"
  run_gate "$(payload "$r" "git commit -m 'use -n for dry run'")"
  [ "$status" -eq 0 ]
  [ -z "$output" ]
}
